# -----------------------------
# Global settings
# -----------------------------
set-environment -g LC_TIME en_US.UTF-8

set -g default-terminal "xterm-kitty"
set -g pane-border-style bg=default
set -g pane-active-border-style bg=default
set -g status-style bg=default
set -g window-style bg=default
set -g window-active-style bg=default
set -sg escape-time 0
set -g history-limit 100000
set -g bell-action any
set -g display-time 4000
set -g status-interval 5
set -g base-index 1
setw -g xterm-keys on
setw -g automatic-rename off
set -g set-titles on
set -g focus-events on
setw -g aggressive-resize on
set -g status on
set -g update-environment 'KITTY_LISTEN_ON'
SET_DEFAULT_SHELL='tmux set-option -g default-shell $TMUX_DEFAULT_SHELL'
if-shell '[ -n "$TMUX_DEFAULT_SHELL" ]' \
  "run-shell '${SET_DEFAULT_SHELL}'"

# -----------------------------
# key bindings
# -----------------------------

unbind c-b
bind R source-file ~/.tmux.conf

set -g prefix c-a
set -g mouse on

# Pane navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Kill all other panes without the current pane and no confirmation
bind-key q kill-pane -a

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \ | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

# Pane navigation in copy mode
bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

# Increase/decrease pane size
bind-key = resize-pane -L 10
bind-key - resize-pane -R 10

# macOS clipboard support
set-option -g set-clipboard external
bind -T copy-mode-vi y send-keys -X copy-pipe "pbcopy"
set-window-option -g mode-keys vi

# Enable copy mode with 'k'
unbind [
bind-key k copy-mode

# Selection modes in copy mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi V send-keys -X select-line
bind -T copy-mode-vi C-v send-keys -X select-block

# Debug level
set -g @debug-level 1

# New session and switch to it
bind-key c new-window -c "#{pane_current_path}"

# -----------------------------
# TPM settings
# -----------------------------

set -g @tpm_plugins_path "~/tmux_plugins"

# set -g status-position top

# List of plugins, press leader + I to install
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'jimeh/tmux-themepack'
set -g @themepack 'powerline/double/blue'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux_plugins/tpm/tpm'
