# Neil's ~/.tmux.conf
# for tmux -V >= 2.9

# -----------------------------
# Global settings
# -----------------------------

# scrollback buffer n lines
set -g history-limit 5000

# listen for activity on all windows
set -g bell-action any

# start window indexing at 1 window so the <prefix> 1 is easier to reach
set -g base-index 1

# tell tmux to use 256 colour terminal
set -g default-terminal "screen-256color"

# xterm-style function key sequences
setw -g xterm-keys on

# control automatic window renaming
setw -g automatic-rename off

# enable wm window titles
set -g set-titles on

# remove <esc> key press delay
set -sg escape-time 0

SET_DEFAULT_SHELL='tmux set-option -g default-shell $TMUX_DEFAULT_SHELL'
if-shell '[ -n "$TMUX_DEFAULT_SHELL" ]' \
  "run-shell '${SET_DEFAULT_SHELL}'"

# -----------------------------
# key bindings
# -----------------------------

unbind c-b
set-option -g prefix c-a
bind-key c-a send-prefix
set -g status-style 'bg=#333333 fg=#5eacd3'

bind r source-file ~/.tmux.conf
set -g base-index 1

set-window-option -g mode-keys vi

set -g @debug-level 1

bind r source-file ~/.tmux.conf

# forget the find window.  that is for chumps
bind-key f run-shell "tmux neww $HOME/.dotfiles/scripts/tmux-sessionizer.sh"

