# Neil's ~/.tmux.conf
# for tmux -V >= 2.9

# -----------------------------
# Global settings
# -----------------------------

# remove <esc> key press delay
set -sg escape-time 0

# scrollback buffer n lines
set -g history-limit 50000

# listen for activity on all windows
set -g bell-action any

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 5

# start window indexing at 1 window so the <prefix> 1 is easier to reach
set -g base-index 1

# tell tmux to use 256 colour terminal
set -g default-terminal "xterm-256color"

# xterm-style function key sequences
setw -g xterm-keys on

# control automatic window renaming
setw -g automatic-rename off

# enable wm window titles
set -g set-titles on

# Focus events enabled for terminals that support them
set -g focus-events on

# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on


SET_DEFAULT_SHELL='tmux set-option -g default-shell $TMUX_DEFAULT_SHELL'
if-shell '[ -n "$TMUX_DEFAULT_SHELL" ]' \
  "run-shell '${SET_DEFAULT_SHELL}'"

# -----------------------------
# key bindings
# -----------------------------

unbind c-b
unbind r
bind r source-file ~/.tmux.conf

set -g prefix c-a
set -g base-index 1
set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
# kill all others panes without current pane and no confirmation
bind-key q kill-pane -a


set-window-option -g mode-keys vi

set -g @debug-level 1

bind r source-file ~/.tmux.conf

# forget the find window.  that is for chumps
bind-key f run-shell "tmux neww $HOME/.dotfiles/scripts/tmux-sessionizer.sh"

TMUX_POWERLINE_THEME=my-theme
set -g status-position top

# List of plugins, press leader + I to install
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'erikw/tmux-powerline'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
